### ISSUE TITLE
The react-native-circle-slider package on npmjs is not from this GitHub repository

### ISSUE THREAD

**Issue by RohanTalip** [raymondchooi/react-native-circle-slider#10]
I'm sure you're probably already aware of this, but https://www.npmjs.com/package/react-native-circle-slider indicates that is a "continuation" of this repository (i.e. not pristine) by [exomemphiz](https://www.npmjs.com/~exomemphiz).

The most recent release is also a year old and I don't see a repository linked for the actual source code used.

At the very least, it could cause confusion for people new to react-native-circle-slider.  Even most of the props are different.

@raymondchooi , do you have any interest in publishing releases to npmjs?  If so, have you tried to reach out to @ExoMemphiz ?  (I notice that there is an account on GitHub with the same name and profile image.)  @ExoMemphiz, where is your source repository for the npmjs package?  Also, should you maybe rename the npmjs package to avoid this confusion?

@raymondchooi, you might want to add some instructions to install this package from the GitHub source (e.g. "npm install https://github.com/raymondchooi/react-native-circle-slider" or "yarn add https://github.com/raymondchooi/react-native-circle-slider"), so people can easily get the unmodified version.  I'm guessing that otherwise, some (most?) people would try to just run "npm install react-native-circle-slider" or "yarn add react-native-circle-slider", which would pull in the modified version, resulting in issues like #9 .

**Comment by xnaveira** [comment]
This comment right here saved me so much time, thank you @RohanTalip!

**Comment by RohanTalip** [comment]
https://www.npmjs.com/package/react-native-circle-slider now returns a 404, so there should be less confusion now.

**Comment by raymondchooi** [comment]
Thanks for the heads up @RohanTalip, I've added the [npm package](https://www.npmjs.com/package/react-native-circle-slider) and updated the instructions in the readme for `npm i react-native-circle-slider` and `yarn add react-native-circle-slider`
