### ISSUE TITLE
In TypeScript panResponder is not defined (Line 13)

### ISSUE THREAD

**Issue by eaglejs** [raymondchooi/react-native-circle-slider#15]
panResponder is not defined at all for the plugin. One has to define it as a property of the class.

```
export default class CircleSlider extends Component {
	panResponder;
	constructor(props) {
		super(props);

		this.state = {
			angle: this.props.value,
		};

		this.panResponder = PanResponder.create({
...
```

**Comment by raymondchooi** [comment]
Thanks for catching! I've converted the whole file to typescript, could you let me know if that works for you?

**Comment by raymondchooi** [comment]
Closing as just checked on updated version and do not see error
