### ISSUE TITLE
I want the same for 33, 100 ,1000 instead of 360 .Do any one has any idea? 

### ISSUE THREAD

**Issue by ShrutiGarg019** [raymondchooi/react-native-circle-slider#6]

**Comment by raymondchooi** [comment]
I'm not sure I get your question but you can use `onValueChange` to edit the values to your needs

**Comment by ShrutiGarg019** [comment]
will try to post video for what i exactly want

**Comment by cloudy-ninja** [comment]
@ShrutiGarg019 Did you solve this problem?

**Comment by cloudy-ninja** [comment]
Here is my solution.
For your purpose, we can customize the _**cartesianToPolar**_ func.
For example, let's suppose to show 1000 instead of 360.
In this case, we can change like this.
```
...
if (x === 0) {
   return y>hC ? 0 : 500;
}
else if (y === 0) {
   return x>hC ? 250 : 750;
}
else {
   const ratio = 1000 / 360;
   return (Math.round((ratio*Math.atan((y-hC)/(x-hC)))*180/Math.PI)/ratio +  (x>hC ? 90 : 270)); }
```
