### ISSUE TITLE
Slider doesn't update on StateChange

### ISSUE THREAD

**Issue by KPS250** [raymondchooi/react-native-circle-slider#7]
This is my Code :
`export default class App extends Component{

  constructor(props) {
    super(props);
    this.state = { progress: 10 };

    // Toggle the state every second
    setInterval(() => (
      this.setState(previousState => (
        { progress: previousState.progress+10 }
      ))
    ), 2000)
  }

  render() {
    return (
      console.log(this.state.progress),
      <View style={styles.container}>
       <CircleSlider
          textColor={'#fff'}
          textSize={1}
          value={this.state.progress}
        />
      </View>
    );
  }
}`

**Comment by raymondchooi** [comment]
Value changes are handled and calculated in the CircleSlider.js, you are trying to change it in a different state. Use `onValueChange` if you want to edit the number

**Comment by rutul089** [comment]
Same slider is not updating value ,
 <CircleSlider
                  value={this.state.playSeconds}
                  dialRadius={70}
                  textSize={0}
                  btnRadius={9}
                  dialWidth={6}
                  max={360}
                  strokeWidth={6}
                  strokeColor={'#C4C4C4'}
                  meterColor={'#EEA499'}
                  onValueChange={this.onSliderEditing}
                />
